server:
  port: 8080

  servlet:
    context-path: /api

spring:

  application:
    name: disaster-alert-service

  datasource:
    url: ${POSTGRE_URL}
    username: ${POSTGRE_USERNAME}
    password: ${POSTGRE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Google

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: "http://localhost:8080/api/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
            provider: kakao
        provider:
          kakao:
            authorization-uri: ${KAKAO_AUTH_URI}
            token-uri: ${KAKAO_TOKEN_URI}
            user-info-uri: ${KAKAO_USER_INFO_URI}
            user-name-attribute: id



  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: alert-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    root: INFO
    org.springframework.data.redis: WARN
    org.springframework.kafka: INFO

    org.springframework.security : DEBUG
    org.springframework.security.oauth2 : DEBUG
    com.example.emergencyassistb4b4.global.security: DEBUG
    com.example.emergencyassistb4b4: DEBUG

  config:
    import: classpath:/.env


kakao:
  api:
    key: ${KAKAO_API_KEY}

jwt:
  issuer: my-app
  secret: MyUltraSecureJwtSecretKeyMustBe32Charsafeweqadb!
  access-token-validity: 900000      # 15분
  refresh-token-validity: 1209600000 # 14일