server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: disaster-alert-service

  datasource:
    url: ${POSTGRE_URL}
    username: ${POSTGRE_USERNAME}
    password: ${POSTGRE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: localhost:9092
    admin:
      properties:
        bootstrap.servers: localhost:9092
    consumer:
      group-id: alert-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client-name: Google

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: "http://localhost:8080/api/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
            provider: kakao

        provider:
          kakao:
            authorization-uri: ${KAKAO_AUTH_URI}
            token-uri: ${KAKAO_TOKEN_URI}
            user-info-uri: ${KAKAO_USER_INFO_URI}
            user-name-attribute: id

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  main:
    allow-bean-definition-overriding: true

kakao:
  api:
    key: ${KAKAO_API_KEY}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: alert-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

jwt:                       # << 여기가 최상위 레벨
  issuer: yourIssuer
  secret: =c3ByaW5nLXNlY3JldC1qd3Qta2V5LXNlcmVzZWN1cmUtMTIzNDU=
  accessTokenValidity: 3600000
  refreshTokenValidity: 86400000

logging:
  level:
    root: INFO
    org.springframework.data.redis: WARN
    org.springframework.kafka: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.amqp: DEBUG
    org.springframework.amqp.rabbit.connection: TRACE
    com.rabbitmq: DEBUG
    com.example.disaster: DEBUG
    com.example.emergencyassistb4b4.global.security: DEBUG
    com.example.emergencyassistb4b4: DEBUG

config:
  import: classpath:/.env
