server:
  port: 8080
  servlet:
    context-path: /api
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/api/auth/oauth2/google"
            scope:
              - profile
              - email
            client-name: Google

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: "http://localhost:8080/api/auth/oauth2/kakao"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
  config:
    import: classpath:/.env[.properties]
  application:
    name: disaster-alert-service
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  issuer: my-app
  secret: MyUltraSecureJwtSecretKeyMustBe32Charsafeweqadb!
  access-token-validity: 900000      # 15분
  refresh-token-validity: 1209600000 # 14일
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: alert-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    root: INFO
    org.springframework.data.redis: WARN
    org.springframework.kafka: INFO
    com.example.disaster: DEBUG